### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TravisHoover** [letsvalidate/api#10]
I'm seeing a 502 Bad Gateway error page when trying to access the website
![capture](https://user-images.githubusercontent.com/18518730/39490633-1733d52c-4d4f-11e8-9dab-64b6539248b0.PNG)

**Comment by hbakhtiyor** [comment]
Sorry for the delay and the issue fixed now.

**Comment by alex-tsx** [comment]
Seems, like it wasn't fixed.
