### ISSUE TITLE
Please disable website cache

### ISSUE THREAD

**Issue by klopp1991** [letsvalidate/api#11]
I scan a weather site time by time. It looks like the websites are cached. Is it possible to disable the cache?

**Comment by hbakhtiyor** [comment]
the hard coded ttl is a week, until expiration it not take any new screenshot, if not passed with `refresh` param,

**Comment by klopp1991** [comment]
How must I use the "refresh" parameter?

**Comment by hbakhtiyor** [comment]
it takes boolean values,
e.g.  https://api.letsvalidate.com/v1/thumbs?url=html5test.com&size=og&refresh=1

**Comment by klopp1991** [comment]
Many thanks for this api and your great, fast support and solution. THANK YOU!
