### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by nntai** [letsvalidate/api#6]
Hi, at first, thank you for great apis.
I got a problem today, i always got 503 service unavailable with thumbnail api. It worked fine last week but i don't know what's happened now.
<img width="1229" alt="screen shot 2017-10-16 at 9 43 50 am" src="https://user-images.githubusercontent.com/15927583/31593083-ab9bb840-b256-11e7-8782-f807086329bc.png">

**Comment by alexmayo** [comment]
This happens often... The so-called 'status tracker' doesnt work and shows the service as being up still. The API is down for me too.

**Comment by hbakhtiyor** [comment]
thank you all for trusting the api ;) 

yeah, the api often down, i'll work to improve it.
@alexmayo because the api uses cloudflare caching layer, and the status tracker can't bypass the layer, i opened feature request there to add dynamic parameter like `&ts={timestamp}`

now the api is working

**Comment by nntai** [comment]
It works fine now. Tks @hbakhtiyor

**Comment by TravisHoover** [comment]
Hello, I am getting the 503 error when trying to use the API. Are there any updates to trying to keep it from going down often?

**Comment by hbakhtiyor** [comment]
now works, looks like auto restarting doesn't work :)

**Comment by TravisHoover** [comment]
Thank you for the quick resolution!

**Comment by TravisHoover** [comment]
It looks like the API is down again :(

**Comment by hbakhtiyor** [comment]
:( 
up again

**Comment by alex-tsx** [comment]
Down again.

**Comment by alex-tsx** [comment]
Down again.
