### ISSUE TITLE
Full mode produces - "code":"004": An internal error accoured.

### ISSUE THREAD

**Issue by yuryev89** [letsvalidate/api#8]
Hello,

First of all thanks a lot for your API, it's amazing.
I've started receiving error with parameter full=true
` {"error":{"code":"004","message":"An internal error accoured."}}`

There are several examples:
- https://api.letsvalidate.com/v1/thumbs?full=true&quality=80&url=thepowerlinegroup.com
- https://api.letsvalidate.com/v1/thumbs?full=true&quality=80&url=skycoin.net 
-  https://api.letsvalidate.com/v1/thumbs?full=true&quality=80&url=syndstrat.com

Could you please check whether it's a bug or my incorrect usage of API.
Best wishes.

**Comment by hbakhtiyor** [comment]
hi, thanks for your kind words :)

now the api is working
for some websites, the headless chrome had been downing

**Comment by yuryev89** [comment]
The issue is resolved. Thank you!
